### ISSUE TITLE
vcf2maf.pl skips running VEP if the VEP VCF file already exists in the temp dir

### ISSUE THREAD

**Issue by raylim** [mskcc/vcf2maf#110]
However, just because a VCF file in the tmp dir with the same name exists, doesn't mean it's the same VCF file with the same variants.  This can result in odd inconsistencies.

**Comment by ckandoth** [comment]
This workaround was necessary for `maf2maf` to properly wrap around `vcf2maf`. I used to print a warning saying something like "Annotated VCF found. Using that instead of rerunning VEP", but users of `maf2maf` would see this warning for each tumor-normal pair, and find it confusing.

One solution is to always rerun VEP and create a new `vep.vcf` by default. But then also add a new argument that allows vcf2maf to use an existing `vep.vcf` file if found.

On the other hand, you're using the same filename for different variant lists, which indicates something badly designed upstream of running vcf2maf. If you can give me a legit use-case where my solution above will be helpful, I can allocate some time to implement this. Thanks much.

**Comment by ckandoth** [comment]
Closing issue. Hopefully this serves as a guide for people running into issues because of this.
