### ISSUE TITLE
ERROR: Invalid Tumor_Sample_Barcode in MAF

### ISSUE THREAD

**Issue by crazyhottommy** [mskcc/vcf2maf#124]
Hi,  
I downloaded the vaf files from GDC by `TCGAbiolinks`
when convert to vcf, error appeared.

```bash
perl /apps/vcf2maf/maf2vcf.pl --input-maf ../GDCdata/TCGA-SKCM/legacy/Simple_nucleotide_variation/Simple_somatic_mutation/0aaab448-a53f-4c40-a7d5-3e9e3e7ccc6e/SKCM_pairs.aggregated.capture.tcga.uuid.automated.somatic.maf --output-dir . --ref-fasta ~/annotations/human/ensemble/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz 
ERROR: Invalid Tumor_Sample_Barcode in MAF: "Binary file ../GDCdata/TCGA-SKCM/legacy/Simple_nucleotide_variation/Simple_somatic_mutation/0aaab448-a53f-4c40-a7d5-3e9e3e7ccc6e/SKCM_pairs.aggregated.capture.tcga.uuid.automated.somatic.maf matches"

```
Any idea? I saw in the code, there are maybe un-allowed characters in the MAF?

Thanks
Tommy

**Comment by ckandoth** [comment]
I downloaded this MAF directly [from here](https://portal.gdc.cancer.gov/legacy-archive/files/0aaab448-a53f-4c40-a7d5-3e9e3e7ccc6e). It came as a `.tar.gz` file, which I unpacked using `tar -zxf`. The resulting folder contained the `.maf` file, on which I ran the following successfully using maf2vcf v1.6.13:
```bash
perl maf2vcf.pl --input-maf SKCM_pairs.aggregated.capture.tcga.uuid.automated.somatic.maf --output-dir . --ref-fasta Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
```
Since your error message describes your MAF as a "Binary file", I suspect your `.maf` is not plain-text. There could be some weird thing that `TCGAbiolinks` is doing. Try running the following Unix command that maf2vcf uses to extract tumor-normal sample IDs from the MAF:
```bash
grep -Eiv "^#|^Hugo_Symbol|^Chromosome|^Tumor_Sample_Barcode" SKCM_pairs.aggregated.capture.tcga.uuid.automated.somatic.maf | cut -f 16,17 | sort -u
```

**Comment by crazyhottommy** [comment]
I guess `TCGAbiolinks` is doing something. I can grep out the samples, but it says binary file again.

```bash
grep -Eiv "^#|^Hugo_Symbol|^Chromosome|^Tumor_Sample_Barcode" SKCM_pairs.ag
gregated.capture.tcga.uuid.automated.somatic.maf | cut -f 16,17 | sort -u | head
Binary file SKCM_pairs.aggregated.capture.tcga.uuid.automated.somatic.maf matches
TCGA-3N-A9WB-06A-11D-A38G-08	TCGA-3N-A9WB-10A-01D-A38J-08
TCGA-3N-A9WC-06A-11D-A38G-08	TCGA-3N-A9WC-10A-01D-A38J-08
TCGA-3N-A9WD-06A-11D-A38G-08	TCGA-3N-A9WD-10A-01D-A38J-08
TCGA-BF-A1PU-01A-11D-A19A-08	TCGA-BF-A1PU-10A-01D-A19A-08
TCGA-BF-A1PV-01A-11D-A19A-08	TCGA-BF-A1PV-10A-01D-A19A-08
TCGA-BF-A1PX-01A-12D-A19A-08	TCGA-BF-A1PX-10A-01D-A19A-08
TCGA-BF-A1PZ-01A-11D-A19A-08	TCGA-BF-A1PZ-10A-01D-A19A-08
TCGA-BF-A1Q0-01A-21D-A19A-08	TCGA-BF-A1Q0-10A-01D-A19A-08
TCGA-BF-A3DJ-01A-11D-A20D-08	TCGA-BF-A3DJ-10A-02D-A20D-08

```

**Comment by ckandoth** [comment]
I see. Could you [take a look at this](https://unix.stackexchange.com/questions/19907/what-makes-grep-consider-a-file-to-be-binary) and see if it helps? Ideally, this needs to be fixed in `TCGAbiolinks`, but if you need a quick workaround, you can manually edit your copy of `maf2vcf.pl` to use `grep -aEiv` instead of `grep -Eiv`.

**Comment by ckandoth** [comment]
Closing this issue, as it's related to `TCGAbiolinks`. Please feel free to add a comment here if you find more information useful to anyone else. Cheers!

**Comment by crazyhottommy** [comment]
Thanks! the workaround did the trick.
