### ISSUE TITLE
From mutlisample vcf, a single tumor is processed in the final MAF while all tumors are in the vep.vcf file

### ISSUE THREAD

**Issue by BTessoulin** [mskcc/vcf2maf#152]
Hi and many thanks for such a useful script, I'm trying to run it on a VCF with multiple samples. 
All VCF were disjoined at first (GatK processing) and tehn were merged into a single VCF, with one allele per line. Of note, all samples are tumors only, without normal counterpart. 

When I launch the straighforward 
`perl vcf2maf.pl --input-vcf gatk_merged_test.vcf --output-maf gat_merged_test.maf `
The vep output file gives me all the genotypes of my samples, with the right names, but the maf outputs all the samples without distinction ("TUMOR").

When trying 
`perl vcf2maf.pl --input-vcf gatk_merged_test.vcf --tuor-id BCN JIM3 --output-maf gat_merged_test.maf`
Only the first sample is processed. 

Maybe I'm wrong but I assumed that vcf2maf could now handle multiSample vcf since several versions. But still I can use the turnaround way you perfectly described into:
[https://www.biostars.org/p/108112/#108816](url)

Many thanks again!

**Comment by ckandoth** [comment]
Hello. You will definitely need to specify `--tumor-id` and/or `--vcf-tumor-id` for vcf2maf to find and extract data from the appropriate genotype columns. The default value of `--tumor-id` is `TUMOR`, which is what you observed in your output.

By design, vcf2maf cannot create a multisample MAF from a multisample VCF. I recommend leaving your per-tumor GATK VCFs disjoined, running vcf2maf on each, and concatenating the resulting MAFs. In general, I recommend storing somatic variants in separate VCFs "per patient". Unlike germline events, somatic events are rarely shared between individuals, and a multisample VCF format becomes inefficient. The only case for a multisample VCF for somatic variants is if the samples are all from the same patient, and you're doing some kind of heterogeneity or phylogeny analysis.

**Comment by BTessoulin** [comment]
Many thanks, I'll do as you suggest. 
Best wishes.

**Comment by jdm204** [comment]
Hi @ckandoth, apologies for resurrecting a closed issue and thank you for maintaining this tool. 

I have the scenario described (multiple tumour samples from the same patient for heterogeneity analysis). 

I tried the `vcf-subset` solution you have specified in other threads and this works fine, but for my VCFs I get identical (by diff) MAFs by simply running `vcf2maf.pl` multiple times, specifying different tumour IDs.

Unless there are situations where this would break, it seems like multiple runs is a slightly more convenient solution to getting from multi-sample VCF -> multi-sample MAF as it doesn't require another tool.

**Comment by ckandoth** [comment]
@jdm204 that seems odd. Can you open a new issue and share a sample with commands to report? And I'll take a look.
