### ISSUE TITLE
--retain-info missing data in MAF file

### ISSUE THREAD

**Issue by bibbers93** [mskcc/vcf2maf#167]
Hi, I am using the following command

``` 
vcf2maf.pl --input-vcf no_chr.vcf --output-maf test.maf --tumor-id Sample1 --ref-fasta ~/.vep/homo_sapiens/91_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --retain-info GT,GQ,SDP,DP,RD,AD,FREQ,PVAL,RBQ,ABQ,RDF,RDR,ADF,AD

```
to generate a maf file from a vcf file. The outputted maf file has columns GT GQ SDP etc. but there is no data from the vcf file in these columns.

**Comment by ckandoth** [comment]
The values of `GT:AD:DP` are in your VCF's genotype column named `Sample1`. The argument `--retain-info` is for extracting data from the your VCF's INFO field. Since you specified `--tumor-id Sample1`, vcf2maf will look in that genotype column for the values of `GT`, `AD`, and `DP`.

The value of `GT` represents zygosity in VCF format. In MAF format, zygosity is represented by the values in columns `Tumor_Seq_Allele1` and `Tumor_Seq_Allele2`. Unlike VCF format, MAF format cannot represent more than two non-reference alleles at the same position.

The value of `DP` ends up in `t_depth` in the MAF format, and the reference/variant allele depths in `AD` (and sometimes in `RD`) end up in `t_alt_count` and `t_ref_count` in the MAF format.

**Comment by bibbers93** [comment]
Hi. I see. But they’re also empty. 

L.I.Bibby

**Comment by bibbers93** [comment]
That being t-depth t-alt and t-ref 

I would like to point out this is the same individual as s1667153@sms.ed.ac.uk 

Thanks,

L.I.Bibby

**Comment by ckandoth** [comment]
Hi LLoyd @bibbers93 - Can you provide a sample VCF? I would like to get to the bottom of this.

**Comment by bibbers93** [comment]
I’ll try and find some sample data 

L.I.Bibby

**Comment by ckandoth** [comment]
Dear people. I will need a sample VCF to debug.

**Comment by batis2ta** [comment]
Dear people you get what you asked for ;) 
[first100lines.txt](https://github.com/mskcc/vcf2maf/files/2446546/first100lines.txt)

**Comment by ckandoth** [comment]
@batis2ta your issue is unrelated to the `--retain-info` option. In your VCF, depths and allele counts live in the genotype column `NT201` with `FORMAT=GT:DP:AF:SB:DP4`. The command that worked was:

```bash
perl vcf2maf.pl --input-vcf first100lines.vcf --output-maf first100lines.vep.maf --tumor-id NT201 --ref-fasta /ifs/depot/pi/resources/genomes/hg19/fasta/hg19.fasta
```

In the resulting MAF, the `DP` values from column `NT201` will end up in `t_depth`. You have a copy of `DP` under the `INFO` column too, but vcf2maf does not need that. Now for `t_ref_count` and `t_alt_count`, the necessary information is in `DP4` which vcf2maf does not (yet) support. As a temporary workaround, use argument `--retain-info DP4` which creates a new column in the MAF named `DP4`.

I will add support for your LoFreq VCFs in https://github.com/mskcc/vcf2maf/issues/196

**Comment by ltang217** [comment]
hi, I have a similar problem. I checked that my vcf file does contain 'GT:AD:AF:DP', but in the converted maf file, some variants get 't_depth/t_ref_count/t_alt_count', but some others not. And this happens on both SNV and small INDELs. Very confusion. Anyone can help look into this? I can provide the sample vcf files. Thanks!

**Comment by richardmpan** [comment]
Dear Cyriac, same problem here. 

perl ~/tools/vcf2maf_GRCh38.pl --input-vcf sample_vcf.txt \
    --output-maf  sample.maf \
    --tumor-id  sample \
    --vep-overwrite \
    --vep-forks=4 \
    --buffer-size=20000

[sample_vcf.txt](https://github.com/user-attachments/files/20620674/sample_vcf.txt)
