### ISSUE TITLE
Error on bioconda vcf2maf

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [mskcc/vcf2maf#169]
HI I try to use the bioconda version (v2maf). Itry to prepare the  code enlight
```
 vep_install.pl -a cf -s homo_sapiens -y GRCh37 -c Database_tutorial2017/vep/
 vep_convert_cache.pl -species homo_sapiens -version 87_GRCh37 -d Database_tutorial2017/vep/

```
I f I try to run on mutect2 vcf I have many errors:
```

vcf2maf.pl --input-vcf mutect2/432.mutect2.vcf --output-maf 432.mutect2.maf --tumor-id 432 --normal-id 433    --ref-fasta  /Database_tutorial2017/vep/homo_sapiens/87_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz  --vep-data  /mnt/mpwork/Database_tutorial2017/vep/ --ncbi-build GRCh37 --cache-version 87 
[E::fai_build3] Cannot index files compressed with gzip, please use bgzip
Could not load fai index of  /Database_tutorial2017/vep/homo_sapiens/87_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz
ERROR: Provided --filter-vcf is missing or empty: /home/maurizio/.vep/ExAC_nonTCGA.r0.3.1.sites.vep.vcf.gz

```
What I miss ? I don't found this data

**Comment by ckandoth** [comment]
Sorry I don't maintain the bioconda version, and I'm not sure who set it up. But try this:
`Cannot index files compressed` - is because you have an older samtools. Get samtools 1.2 or newer.
`ERROR: Provided --filter-vcf is missing` - Follow the instructions at [this gist](https://gist.github.com/ckandoth/d135aec7afd8edd73f572584cbf23f5c) to download the missing file.

**Comment by bioinfo-dirty-jobs** [comment]
@ckandoth 
I use the bioconda version and I have this version of samtools
`samtools                  1.5                           0    dranew`
