### ISSUE TITLE
ExAC VEP annotations not parsed due to MAF column names

### ISSUE THREAD

**Issue by loreseeker** [mskcc/vcf2maf#172]
Hello,

I ran into an issue trying to obtain ExAC VEP annotations in the output MAF file (vcf2maf 1.6.16 with ensembl-vep 90.5, using cache 85). Only the ExAC_AF column was being populated, whereas ExAC_AF_AFR, ExAC_AF_AFR, ExAC_AF_EAS, ExAC_AF_FIN, ExAC_AF_NFE, ExAC_AF_OTH, and ExAC_AF_SAS	columns remained blank. 

As these columns are named differently in VEP-annotated VCFs (ExAC_AFR_AF, ExAC_AMF_AF, etc.) I sed replaced the column names in the vcf2maf.pl script, as a workaround to match the VEP VCF CSQ ExAC field names, and was able to get the allele frequencies I wanted in the corresponding MAF columns. I'm not good with perl, but I'm guessing the script inherits column names from the VCF file if it can match them to the provided MAF header strings, so the header might need updating in the script? Just thought you guys might want to know about it.

**Comment by ckandoth** [comment]
Thanks @loreseeker. These column names are from an older version of VEP. And we left them unchanged, because we technically override VEP's ExAC data with our own modified ExAC VCF, with false-positives removed - somatic events from clonal hematopoiesis. For more info, see the section [in this gist](https://gist.github.com/ckandoth/5390e3ae4ecf182fa92f6318cfa9fa97) where we download and modify the `ExAC_nonTCGA.r0.3.1` VCF. This modified VCF must be passed into vcf2maf using the `--filter-vcf` argument.

If what you observe is not fully explained above, then let me know, and I'll troubleshoot. Otherwise, we'll close this ticket.

**Comment by loreseeker** [comment]
Thank you for the explanation. I assumed that --filter-vcf file was used for setting common_variant tag in the FILTER column and didn't realize VEP ExAC annotations were also being replaced from this file. I was running vcf2maf without the filter-vcf file (the tool didn't seem to mind, that's what threw me off). I'll close the ticket now. Thanks again!
