### ISSUE TITLE
Annotation prioritization

### ISSUE THREAD

**Issue by fpbarthel** [mskcc/vcf2maf#201]
I noticed that the `vcf2maf.pl` does a lot of prioritization to select the optimal annotation for each variant. How is this different (better than?) from using the `--most_severe` VEP parameter?

**Comment by ckandoth** [comment]
Good question! It is meant to allow us more granular control over what consequence we prefer to prioritize. From [this page](https://useast.ensembl.org/info/genome/variation/prediction/predicted_data.html), the VEP authors say: `This [severity] ordering is necessarily subjective and API and VEP users can always get the full set of consequences for each allele and make their own severity judgement.`

vcf2maf users are mostly working with somatic/cancer variants. VEP users are mostly working with germline/mendelian variants, or other species. Early versions of VEP, prioritized variant consequences in a way we disagreed with for cancer, and that was the whole reason for [vcf2maf v1](https://github.com/mskcc/vcf2maf/tree/v1.1.0) where I said `This project is an attempt to make the selection criteria smarter, reproducible, and more configurable`.

But that has since converged, and we like VEP's `most_severe` prioritization, though we still don't agree with the `canonical` transcripts they select for each gene. For `vcf2maf v1.7.0` I plan to depend entirely on VEP for variant effect prioritization. But I don't know when I'll have time to implement that.

**Comment by fpbarthel** [comment]
Thanks for the explanation!
