### ISSUE TITLE
error when using dockerfile

### ISSUE THREAD

**Issue by michalinbar** [mskcc/vcf2maf#255]
Hi,

I'm trying to use the docker in the latest release.

This is what I used to run the docker:

docker run -it -v "/home/mic/cbioportal/resources/tmp/sharett_exomes/tmp/test.maf:/test/test.maf:ro" -v "/home/mic/tools/vcf2maf/mskcc-vcf2maf-bbe39fe/out:/outdir" b914c1470da6 /bin/bash

and within the container ran the command:

root@22715488429f/opt # perl ./maf2maf.pl --input-maf /test/test.maf --output-maf /outdir/out.maf

I get the following error:

ERROR: Provided --ref-fasta is missing or empty: //.vep/homo_sapiens/91_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz

thanks!!

**Comment by SRodenburg** [comment]
I think you should map your vep-cache directory to /.vep/ in your Docker container

**Comment by ckandoth** [comment]
Thanks @SRodenburg. That's correct. @michalinbar, assuming you stored the VEP cache and reference FASTA in the default path `~/.vep`, you can map it to `/.vep` within the container where `/` is the home directory of the root user within the container. Then run maf2maf using docker as follows:
```
docker run --rm -v $HOME/.vep:/.vep -v $HOME/cbioportal/resources/tmp/sharett_exomes/tmp:/test -w /test b914c1470da6 perl maf2maf.pl --input-maf test.maf --output-maf test.vep.maf
```
Notice how you can use `-w` to specify the working directory within the container, so that the file paths can be relative to that.
