### ISSUE TITLE
vcf2maf can not report VEP custom database annotation?

### ISSUE THREAD

**Issue by tangwei1129** [mskcc/vcf2maf#274]
I have a question about VCF2MAF, I used VEP to annotate the VCF file with new annotation of gnomAD genomes data.
 
$ vep  -i Sample_15120+Sample_15121.FINALmutect2.vcf  --vcf  -o example.vcf  --offline  --cache  --force_overwrite  --fork 16  --dir_cache /path/VEP/customDB  --species human  --assembly GRCh38  --fasta  customDB/GRCh38.d1.vd1.fa  --af_gnomad  --custom  /path/VEP/customDB/gnomad.genomes.r2.1.1.sites.liftover_grch38.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH,variant_type,segdup
 
And the output vcf has the information with the gnomad genome info.
 
Then I used the vcf2maf to convert to maf. But those information from gnomad genome did not show up
$ vcf2maf.pl   --input-vcf example.vcf   --output-maf example.maf   --inhibit-vep   --ref-fasta  customDB/GRCh38.d1.vd1.fa --tumor-id Sample_15120 --normal-id Sample_15121  --vep-forks 16
 
Even I used the –retain-info to specify the INFO I want, it only added to the header, but no information still for last three columns.
$ vcf2maf.pl   --input-vcf example.vcf   --output-maf example1.maf   --inhibit-vep   --ref-fasta  customDB/GRCh38.d1.vd1.fa --tumor-id Sample_15120 --normal-id Sample_15121  --vep-forks 16 --retain-info gnomADg,gnomADg_variant_type,gnomADg_segdup

but if I --retain-info CSQ, it will product all the information without separation.
 
Do you know how to fix the problem to have custom database shown up in the MAF file?

Thank you very much,

Wei

**Comment by djb17** [comment]
I'm running into a similar issue when trying to add additional columns from VCF files generated from VEP utilizing dbNSFP plugin. It seems like `--retain-info` is not working properly since it adds columns, but no corresponding values for the columns.

**Comment by alanhoyle** [comment]
I've created a pull request: #282 which addresses this issue because it's one we've also run into.  

The issue you're running into is that VEP saves your annotations into the `INFO` column, but only inside the `CSQ=` subsection.  VCF2MAF doesn't handle those in its default configuration, as it hardcodes the `CSQ` fields into an `@ann_cols` variable.  The pull request addresses this by doing the following:

1. adding `--vep-custom STRING` and `--vep-config FILE` options that get passed through into subprocess like: `vep --custom STRING --config FILE` subprocess
2. adding `--retain-ann COMMA,SEP,VALUES` which allows you to specify which `CSQ` values to pass into the MAF.  

In @tangwei1129 's example, you'd specify `--vep-custom /path/VEP/customDB/gnomad.genomes.r2.1.1.sites.liftover_grch38.vcf.gz,gnomADg,vcf,exact,0,AF_AFR,AF_AMR,AF_ASJ,AF_EAS,AF_FIN,AF_NFE,AF_OTH,variant_type,segdup --retain-ann gnomADg_AF_AFR,gnomADg_AF_AMR,gnomADg_AF_ASJ,gnomADg_AF_EAS,gnomADg_AF_FIN,gnomADg_AF_NFE,gnomADg_AF_OTH,gnomADg_variant_type,gnomADg_segdup`

**Comment by tangwei1129** [comment]
Hi Alan,
Super helpful. Much appreciated.
should I download a new version of vcf2maf to test the functionality?
Thanks


Alan Hoyle ***@***.***> 于2021年4月14日周三 下午12:22写道：

**Comment by alanhoyle** [comment]
I'm not 100% certain, but I think the easiest way would be to download my forked version to test it out.  I'm not an expert in github, so there's probably some way that you could download and test from the pull request.  Note that I'm not one of the main developers/maintainers, but we use it at our center.  

Link to my fork:  

https://github.com/alanhoyle/vcf2maf

**Comment by tangwei1129** [comment]
thank you, i will test your fork version.

Alan Hoyle ***@***.***> 于2021年4月14日周三 下午1:56写道：

**Comment by alanhoyle** [comment]
@tangwei1129 , any feedback on my fork/pull request? #282   Did it work for you?

**Comment by tangwei1129** [comment]
No, not yet.
Previously, we tweeted a little bit down the pipeline to make it work.
I will keep you posted when we go back to change it.
Many thanks.


Alan Hoyle ***@***.***> 于2021年4月19日周一 下午4:49写道：

**Comment by ckandoth** [comment]
I tested https://github.com/mskcc/vcf2maf/pull/282 successfully as follows and merged it into the `main` branch. Thanks @alanhoyle. I will release shortly as v1.6.21. Closing this issue.

**Comment by alanhoyle** [comment]
I don't think my implementation will handle multiple `--vep-custom` lines.  Merging them into a single config file and use `--vep-config` would work I think.

**Comment by Setfelix** [comment]
Great additions. `--retain-ann` also works for keeping columns from running VEP with a plugin. I just added dbNSFP columns to my MAF, `--retain-info` did not work for me. Thanks

**Comment by stevekm** [comment]
running with `--retain-info gnomADg_AF` seems to have worked for me
