### ISSUE TITLE
vcf2maf prioritises 3'UTR over missense variant

### ISSUE THREAD

**Issue by lconde-ucl** [mskcc/vcf2maf#278]
Hi,

I am using vcf2maf (v1.6.9) to annotate and generate a MAF file for my variants. I noticed there is a variant that VEP annotates as missense or 3'UTR depending on the gene/transcript, but for some reason, the output MAF file is picking the 3'UTR annotation over the missense. 

This is how I'm running vcf2maf:

```
~/vcf2maf-1.6.19/vcf2maf.pl --input-vcf test.vcf --output-maf test.maf \
--species homo_sapiens --ncbi-build GRCh38 --filter-vcf 0 \
--vep-path ~/github_reps/vep/102/ensembl-vep/ \
--vep-data ~/ensembl/caches_vep/102_GRCh38/ \
--ref-fasta ~/ensembl/caches_vep/102_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz 
```

and I'm attaching a test VCF (with just this one variant), as well as the resulting VEP.VCF and MAF outputfiles. For ease of understanding, the relevant columns in the resulting MAF are:

**Hugo_Symbol**: KCNK12
**Variant_Classification**: 3'UTR
**all_effects**: 
MSH2,missense_variant,p.Gln915Arg,ENST00000645506,;MSH2,missense_variant,p.Gln915Arg,ENST00000406134,;KCNK12,3_prime_UTR_variant,,ENST00000327876,NM_022055.2;MSH2,missense_variant,p.Gln915Arg,ENST00000646415,;MSH2,missense_variant,p.Gln915Arg,ENST00000645339,;MSH2,3_prime_UTR_variant,,ENST00000644092,;MSH2,3_prime_UTR_variant,,ENST00000644900,;,regulatory_region_variant,,ENSR00001031143

So I wonder why is picking "KCNK12,3_prime_UTR_variant" instead of "MSH2,missense_variant"?

Thanks
Lucia
[issue_vcf2maf.zip](https://github.com/mskcc/vcf2maf/files/6111312/issue_vcf2maf.zip)

**Comment by ckandoth** [comment]
Hi @lconde-ucl. Thanks for providing test data. [Click here](https://github.com/mskcc/vcf2maf/blob/v1.6.19/vcf2maf.pl#L751-L775) to see how vcf2maf v1.6.19 prioritizes effects. And click [here](https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000095002) and [here](https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000184261) to see the transcript tables for MSH2 and KCNK12.

Since you did not use `--custom-enst` to specify preferred isoform per gene, vcf2maf uses VEP's "canonical" isoform per gene (defined as longest transcript with a CCDS ID). This is OK, but for MSH2, the canonical isoform is ENST00000233146 which is nowhere near the mutation. So vcf2maf ends up choosing the "worst affected VEP canonical isoform with a gene symbol". This is ENST00000327876 of gene KCNK12.

My hunch is that this mutation is not altering MSH2, but let me know if you have experimental evidence or RNA-seq that shows this mutation altering MSH2 mRNA. You can always specify one or more transcripts in `--custom-enst` per gene.
