### ISSUE TITLE
docker clone

### ISSUE THREAD

**Issue by complexgenome** [mskcc/vcf2maf#355]
The step in readme about docker doesn't clone. `git clone git@github.com:mskcc/vcf2maf.git`

Following code worked for me:
`git clone https://github.com/mskcc/vcf2maf.git`

**Comment by ckandoth** [comment]
You are cloning the GitHub repo in this step, not the docker image. You can clone repos from GitHub using either HTTPS or SSH. Both have pros and cons, but I prefer SSH since keys are easier to manage than Access Tokens for HTTPS. [Read more here](https://www.howtogeek.com/devops/should-you-use-https-or-ssh-for-git/).
