### ISSUE TITLE
splice_region_variant has lower priority than synonymous_variant

### ISSUE THREAD

**Issue by jjgao** [mskcc/vcf2maf#44]
17:g7579312C>A is annotated as silent mutation, but according to VEP the most severe consequence is splice_region_variant. 

http://grch37.rest.ensembl.org/vep/human/hgvs/17:g7579312C%3EA?content-type=application/json

I think we should assign a lower priority to synonymous_variant.

Alternatively, is it possible to assign the most_severe_consequence from VEP as the annotated consequence in MAF?

**Comment by ckandoth** [comment]
Sequence ontology terms `splice_donor_variant` and `splice_acceptor_variant` are for calls within 1-2 bp from the splice junction, into the intron. These are equivalent to the TCGA MAF term `Splice_Site`.

On the other hand, `splice_region_variant` is 3-8 bps into the intron which should be less severe than a `synonymous_variant`. However, `splice_region_variant` also includes 1-3 bps into the coding exon, which should be higher priority than a `synonymous_variant` elsewhere in the exon. However, the open question is - what do we call it in the MAF format, which doesn't have an equivalent.

For v1.7, a major change is to remove the custom EffectPriority and BiotypePriority, and instead rely on VEP to do the ranking. As of VEP v79, vcf2maf uses the arguments `--flag_pick_allele --pick_order canonical,tsl,biotype,rank,ccds,length` when running VEP. This gets us very close to the ranking we already do in EffectPriority and BiotypePriority. `17:g7579312C>A` will then be annotated as `splice_region_variant` and vcf2maf will use the term Splice_Region to describe it. I'll put in a separate request to TCGA, to include that as a valid `Variant_Classification`.

**Comment by jjgao** [comment]
Sounds good. Thanks!

**Comment by ckandoth** [comment]
Released v1.6.7 with a fix. MAFs from this release will contain a `Variant_Classification` named `Splice_Region` equivalent to SO term `splice_region_variant`.

This does not comply with MAF spec v2.4. But per a chat with a TCGA lead, we can unofficially make as many changes as we like, that don't break too many existing MAF parsers. If we want to make it official, we have to wait for the responsibility to transfer from NCI's TCGA to NCI's GDC, before we propose changes to the MAF specs.

Regd v1.7 mentioned earlier in this thread, it's backlogged because the VEP way of prioritizing effects needs more testing before we use it across MSKCC.
