### ISSUE TITLE
Report all possible consequences per transcript in the all_effects column

### ISSUE THREAD

**Issue by j-hudecek** [mskcc/vcf2maf#63]
We have a VCF file with this line:

    chr7  116412043       .       G       C       100.00  PASS    DP=7248;EXON;FC=Unknown_1028,Unknown_1010;GI=MET,MET;TI=NM_001127500,NM_000245;;CSQ=C|missense_variant&splice_region_variant|MODERATE|MET|ENSG00000105976|Transcript|ENST00000397752|protein_coding|14/21||ENST00000397752.3:c.3028N>C|ENSP00000380860.3:p.Asp1010His|3228/6635|3028/4173|1010/1390|D/H|Gat/Cat||1||1|||SNV|1|HGNC|7029|||CCDS43636.1|ENSP00000380860|MET_HUMAN|Q9UEJ3_HUMAN&B4DPY6_HUMAN&B4DLF5_HUMAN|UPI000020F975|NM_000245.2&NM_001127500.1|1|deleterious(0.02)|probably_damaging(0.976)|hmmpanther:PTHR24416:SF261&hmmpanther:PTHR24416&PIRSF_domain:PIRSF000617||||||||||||||||||||||||||,C|downstream_gene_variant|MODIFIER|MET|ENSG00000105976|Transcript|ENST00000422097|protein_coding|||||-/688|-/645|-/214||||1|2080|1|cds_start_NF||SNV|1|HGNC|7029||||ENSP00000398776||H7C174_HUMAN|UPI000155D67D||1|||||||||||||||||||||||||||||,C|intron_variant|MODIFIER|MET|ENSG00000105976|Transcript|ENST00000454623|protein_coding||2/2|ENST00000454623.1:c.283+335N>C||-/475|-/475|-/158||||1||1|cds_start_NF&cds_end_NF||SNV|1|HGNC|7029||||ENSP00000398140||H7C130_HUMAN|UPI000155D67E||1|||||||||||||||||||||||||||||,C|missense_variant&splice_region_variant|MODERATE|MET|ENSG00000105976|Transcript|ENST00000318493|protein_coding|14/21||ENST00000318493.6:c.3082N>C|ENSP00000317272.6:p.Asp1028His|3269/4632|3082/4227|1028/1408|D/H|Gat/Cat||1||1||1|SNV|1|HGNC|7029|YES||CCDS47689.1|ENSP00000317272|MET_HUMAN|Q9UEJ3_HUMAN&B4DPY6_HUMAN|UPI000014033E||1|deleterious(0.01)|probably_damaging(0.994)|hmmpanther:PTHR24416:SF261&hmmpanther:PTHR24416&PIRSF_domain:PIRSF000617||||||||||||||||||||||||||,C|regulatory_region_variant|MODIFIER|||RegulatoryFeature|ENSR00001800475|promoter_flanking_region|||||||||||1|||||SNV|1||||||||||||||||||||||||||||||||||||||||    GT:GQ:AD:VF:NL:SB:GQX:AF        0/1:100:6043,1199:0.1654:20:-100.0000:100:0.166

Note that it's annoted by VEP as both missense and splice region variant. The resulting MAF line is

    MET       0       .       GRCh37  chr7    116412043       116412043       +       Missense_Mutation       SNP     G       G       C       novel           TUMOR   NORMAL  G       G                   c.3028N>C        p.Asp1010His    p.D1010H        ENST00000397752 14/21   7242    6043    1199                            MET,missense_variant,p.Asp1010His,ENST00000397752,NM_000245.2,NM_001127500.1;MET,missense_variant,p.Asp1028His,ENST00000318493,;MET,intron_variant,,ENST00000454623,;MET,downstream_gene_variant,,ENST00000422097,;  C       ENSG00000105976 ENST00000397752 Transcript      missense_variant        3228/6635       3028/4173       1010/1390       D/H     Gat/Cat              1               1       MET     HGNC    7029    protein_coding          CCDS43636.1     ENSP00000380860 MET_HUMAN       Q9UEJ3_HUMAN,B4DPY6_HUMAN,B4DLF5_HUMAN  UPI000020F975   NM_000245.2,NM_001127500.1      deleterious(0.02)    probably_damaging(0.976)        14/21           hmmpanther:PTHR24416:SF261,hmmpanther:PTHR24416,PIRSF_domain:PIRSF000617                                                                                                            MODERATE         SNV

It's type is Missense_Mutation. 
The fact that this mutation is at a splicing site is more interesting than it being a missense. Vcf2maf should mark it as Splice_site.

**Comment by ckandoth** [comment]
Thanks for your interest. I'm using [this subjective ranking](http://useast.ensembl.org/info/genome/variation/predicted_data.html#consequences) that prioritizes `missense_variant` over `splice_region_variant`. In MAF format, `Splice_Site` is defined as a variant within 2bp of the splice junction. [Broad's Oncotator](http://gatkforums.broadinstitute.org/wdl/discussion/4325/how-are-splice-sites-annotated) interprets this as 2bp either on the exon or intron side. While [WashU's annotator](https://github.com/genome/genome/blob/master/lib/perl/Genome/Model/Tools/Annotate/TranscriptVariants/Base.pm#L413) interprets this as 2bp into the intron only. VEP does the same, but tags them as `splice_acceptor_variant` or `splice_donor_variant`, which makes more sense. For variants 1-3bp into the exon (and 3-8bp into intron), VEP calls those `splice_region_variant` with a lower priority, because they are less likely to alter splicing than a variant at the donor/acceptor sites. Notice the significantly lower lack of consensus of bases in the exons:

![alt text](http://www.geneinfinity.org/images/splicing.jpg)

But if you look carefully, the exonic bp right next to a splice donor site, does appear to select for a `G`. And the [variant you provided](http://feb2014.archive.ensembl.org/Homo_sapiens/Location/View?r=7:116412042-116412045), changes that same `G` to a `C`. This is more likely to be deleterious than a missense variant, but less than at an acceptor/donor site. So calling it a `Splice_Site` is not really the answer here. It's really just a rare exception to the subjective generalizations we make when automating annotation. For example, a synonymous variant at a miRNA binding site can disrupt target recognition, but we still annotate them as `synonymous_variant`, because it's not yet fully understood. It's up to the user to make their own judgement on variant severity.

It's not incorrect to call this a `missense_variant`, but I'd like to see `splice_region_variant` also reported in the `all_effects` column. I'll work on that, so that users have enough information to make a curated judgement on what's really going on.

An ideal annotator would have matched RNA-seq to see if this `G>C` variant is actually altering splicing, and then decide between calling it a `missense_variant` or something like `splice_donor_adjacent_exon_bp_variant`. But that's a lot of work. :)

**Comment by j-hudecek** [comment]
Thank you for the informative write up. We're using vcf2maf in a pipeline that imports our VCF files to cBioPortal so we will probably need to add a manual annotation step to catch stuff like this.  Apparently, there is mRNA evidence that mutation at that position can lead to skipping exon 14 activating MET1, so this is somatic.

**Comment by ckandoth** [comment]
Note that my upcoming update will edit column 51 to show all possible consequences on the canonical transcript. In your example, it will contain `missense_variant,splice_region_variant`. This makes it easier for your downstream code to catch this. I've discussed this with @jjgao before, and the plan is to abandon the MAF `Variant_Classification` in favor of the Sequence Ontology terms in column 51. It also makes sense to display the multiple possible consequences per transcript in the cBioPortal.

**Comment by ckandoth** [comment]
With commit 8fb3746234ad34b71ede126c8c7fa4fe4f342d2f, the `Consequence` column is now a comma-delimited list of all possible SO terms on the canonical isoform. I can't do the same for all possible isoforms in the `all_effects` column, because some users parse that, and expect one consequence per isoform. But "all possible effects on the canonical isoform" is sufficient for most situations, including the example you started this thread with. Re-open this thread, if you think I missed something. Thanks again.
