### ISSUE TITLE
vcf2maf produced invalid Variant_Classification values Splice_Region

### ISSUE THREAD

**Issue by kjnousia** [mskcc/vcf2maf#88]
This is inconvenient as downstream software genome music fails if maf contains invalid values.

**Comment by ckandoth** [comment]
Sorry for this. Though `Splice_Region` is not in the official TCGA MAF specs, this was discussed with some TCGA leads, and has their unofficial blessing - it fills an important gap. Particularly of silent/missense mutations <2bp from a splice junction. For example, see [this variant in MET](https://github.com/mskcc/vcf2maf/issues/63), and [this paper about splice-altering synonymous muts](http://www.cell.com/cell/fulltext/S0092-8674%2814%2900145-7).

A quick but safe fix is to do the following to your MAF, before running MuSiC:
1. Remove all `Splice_Region` (Column 9) variants that have the tag `intron_variant` under `Consequence` (Column 51). If you already exclude non-exonic calls, you don't need to do this step.
2. Rename all remaining `Splice_Region` variants as `Splice_Site` (Column 9). These will be exonic silent mutations <2bp from splice junctions.

Alternatively, I can update MuSiC to support `Splice_Region`. I assume you are using this - https://github.com/ding-lab/MuSiC2 - but let me know otherwise.

**Comment by ckandoth** [comment]
Closing issue. Please try one of the possible solutions I listed above. Reopen this issue if you still need help on this topic. Open a new issue, if you have an unrelated problem.
